# Generated by Django 5.0.6 on 2024-05-22 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='destiantion',
            new_name='destination',
        ),
    ]
