# Generated by Django 5.0.6 on 2024-05-23 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='firts',
            new_name='first',
        ),
    ]
